server:
  port: 8083
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  datasource:
    #    ���ݿ�����
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.102:3306/panlll?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    #    ���ӳ�����
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1000 #���������,Ĭ��ֵ10.
      minimum-idle: 200 #��С�������ӣ�Ĭ��ֵ10.
      connection-timeout: 60000 #���ӳ�ʱʱ��(����),Ĭ��ֵ30��.
      #�������ӳ�ʱʱ�䣬Ĭ��ֵ600000(10����),ֻ�п�����������������������ҿ���ʱ�䳬����ֵ���Żᱻ�ͷ�
      #������ڵ��� max-lifetime �� max-lifetime>0,��ᱻ����Ϊ0.
      idle-timeout: 600000
      max-lifetime: 3000000 #���������ʱ��,Ĭ��ֵ30����.����Ӧ�ñ�mysql���õĳ�ʱʱ���


